development: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  reconnect: true
  url:  <%= "postgres://aact:aact@aact-dev.cr4nrslb1lw7.us-east-1.rds.amazonaws.com:5432/aact" %>

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  reconnect: true
  url:  <%= "postgres://aact:aact@aact-dev.cr4nrslb1lw7.us-east-1.rds.amazonaws.com:5432/aact" %>

staging: *deploy


